apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Base64 encoded values
  API_ID: <API_ID_BASE64>
  API_HASH: <API_HASH_BASE64>
  HH_CLIENT_ID: <HH_CLIENT_ID_BASE64>
  HH_CLIENT_SECRET: <HH_CLIENT_SECRET_BASE64>
